version: 2.1


orbs:
  maven: circleci/maven@1.4.1
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-ea-buster-node-browsers-legacy  # Utilisation de l'image Docker avec Java 17

    steps:
      - checkout  # Récupère le code source du dépôt

      # Exécution des tests unitaires avec Maven
      - run:
          name: Run Unit Tests
          command: mvn test -X
      - run:
          name: Generate Coverage Report
          command: mvn jacoco:report
      - run:
          name: Upload Coverage Report
          command: bash <(curl -s https://codecov.io/bash)
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Deploy Javadoc to GitHub Pages
          command: |
            git config --global user.email "romain.rigaud@alumni.univ-avignon.fr"
            git config --global user.name "romain-rigaud"
            mv target/site/apidocs/ docs/
            git checkout --orphan gh-pages
            git add -f docs/
            git commit -m "Deploy Javadoc to GitHub Pages"
            git push origin :gh-pages
            git push origin gh-pages

workflows: # Définition des workflows
  version: 2
  upload-to-codecov:
    jobs:
      - build
  maven_test:
    jobs:
      - build:
          filters:
            branches:
              only: master