version: 2.1


orbs:
  maven: circleci/maven@1.4.1
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-ea-buster-node-browsers-legacy

    steps:
      - checkout

      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Run Unit Tests
          command: mvn test -X
      - run:
          name: Generate Coverage Report
          command: mvn jacoco:report
      - run:
          name: Upload Coverage Report
          command: bash <(curl -s https://codecov.io/bash)
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: docs/
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "romain.rigaud@alumni.univ-avignon.fr"
            git config user.name "romain-rigaud"
      - add_ssh_keys:
          fingerprints:
            - "SHA256:ydwMp9Q0qd9Hmc6WNqC4c/eMRTO6EsW3muHgCxFlwCs"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist docs/

workflows:
  version: 2
  maven_test:
    jobs:
      - build:
          filters:
            branches:
              only: master
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - docs-deploy:
          requires:
            - build