version: 2.1


orbs:
  maven: circleci/maven@1.4.1
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-ea-buster-node-browsers-legacy

    steps:
      - checkout

      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Run Unit Tests
          command: mvn test -X
      - run:
          name: Generate Coverage Report
          command: mvn jacoco:report
      - run:
          name: Upload Coverage Report
          command: bash <(curl -s https://codecov.io/bash)
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Install gh-pages
          command: sudo npm install -g --silent gh-pages@2.0.1
      - run:
          name: Install and configure dependencies
          command: |
            git config user.email "romain.rigaud@alumni.univ-avignon.fr"
            git config user.name "romain-rigaud"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist docs/_build/html

workflows:
  version: 2
  upload-to-codecov:
    jobs:
      - build
  maven_test:
    jobs:
      - build:
          filters:
            branches:
              only: master